import type { Client } from "./types.js";

/** Рекламодатели перенесены из citi_ads/src/game/clients.ts. */
export const CLIENTS: readonly Client[] = [
  {
    id: "zerno",
    name: "Кофейня «Зерно»",
    mark: "ЗН",
    category: "Кофейня",
    tagline: "Кофе, который будит весь район",
    offer: "С 7:00 до 10:00 каждый будильник — капучино со скидкой 20%. Просто покажите этот билборд бариста.",
    color: "#d08a3e",
    ink: "#26160a",
    domain: "zerno.coffee",
  },
  {
    id: "gym24",
    name: "GYM 24",
    mark: "24",
    category: "Фитнес-клуб",
    tagline: "Качалка у дома. Круглосуточно",
    offer: "Первый месяц за 990 ₽ при подписке с билборда. Турникеты не спят — и ты не спи.",
    color: "#b8d435",
    ink: "#1a2205",
    domain: "gym24.fit",
  },
  {
    id: "pizzamotor",
    name: "Пицца Мотор",
    mark: "ПМ",
    category: "Пиццерия",
    tagline: "Быстрее разгона до сотни",
    offer: "Вторая пицца в подарок по промокоду РАЛЛИ. Печь разогрета, мотор заведён.",
    color: "#e0432f",
    ink: "#fff1e6",
    domain: "pizzamotor.food",
  },
  {
    id: "garage77",
    name: "Гараж 77",
    mark: "Г77",
    category: "Автосервис",
    tagline: "После нас едешь как с завода",
    offer: "Диагностика бесплатно по будням до 12:00. Увидел щит — заезжай, кофе за наш счёт.",
    color: "#4f9dd8",
    ink: "#06121f",
    domain: "garage77.auto",
  },
  {
    id: "kosmos",
    name: "Кинотеатр «Космос»",
    mark: "КС",
    category: "Кинотеатр",
    tagline: "Большое кино в трёх кварталах от тебя",
    offer: "Вечерние сеансы по средам — 199 ₽. Попкорн по размеру билборда… почти.",
    color: "#3d4fb5",
    ink: "#e9edff",
    domain: "kosmos.cinema",
  },
  {
    id: "britva",
    name: "Барбершоп «Бритва»",
    mark: "БР",
    category: "Барбершоп",
    tagline: "Стрижка, пока греется мотор",
    offer: "Королевское бритьё + кофе — 990 ₽. Записи нет: увидел место — заходи.",
    color: "#333a44",
    ink: "#e8c56a",
    domain: "britva.barber",
  },
  {
    id: "letuchka",
    name: "Доставка «Летучка»",
    mark: "ЛТ",
    category: "Доставка",
    tagline: "Доставим, пока стоишь на светофоре",
    offer: "Доставка 0 ₽ на первый заказ. Курьеры быстрее голубей — проверено районом.",
    color: "#29c46b",
    ink: "#062b16",
    domain: "letuchka.delivery",
  },
  {
    id: "denta",
    name: "Стоматология «Дента+»",
    mark: "Д+",
    category: "Клиника",
    tagline: "Улыбка, которую видно с трассы",
    offer: "Чистка и осмотр — 1 490 ₽ до конца месяца. Щит не врал: действительно не больно.",
    color: "#39c6d8",
    ink: "#04262c",
    domain: "denta.plus",
  },
  {
    id: "shashechka",
    name: "Такси «Шашечка»",
    mark: "ШШ",
    category: "Такси",
    tagline: "Подача за 3 минуты в любом районе",
    offer: "Поездки до 3 км — 99 ₽ по ночам. Водители знают каждый billboard лично.",
    color: "#f2c230",
    ink: "#231a02",
    domain: "shashechka.taxi",
  },
];
